name: Consumer Pact CI

on:
  workflow_dispatch:

jobs:
  pact-consumer-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Run Consumer Pact Tests
        run: mvn test

      - name: Upload Pact Files
        uses: actions/upload-artifact@v4
        with:
          name: pacts
          path: target/pacts
